#! /usr/bin/env bash

#if [ -e .version ] ; then
#  cat .version
#  exit 0
#fi

branch=`git branch | grep "*" | awk '{print $2}' | sed 's,\/.*,,'`
echo $branch

# Check for git on the system
git=`which git`

if [ "$git" = "" ] ; then
  echo "ERROR! You must have git installed to use this script!!!"
  exit
fi

git_patch=`git describe | sed 's,^.*[\-]\([0-9]\)*\-.*,\1,g'`
git_abbrev=`git describe --abbrev=0`

if [ "$git_patch" != "$git_abbrev" ] ; then
  echo "$git_abbrev.$git_patch"
else
  echo $git_abbrev
fi
