#! /usr/bin/env bash

if [ -e .version ] ; then
  cat .version
  exit 0
fi

# Check for git on the system
git=`which git`

if [ "$git" = "" ] ; then
  echo "ERROR! You must have git installed to use this script!!!"
  exit
fi

echo `git describe | sed 's,\-.*,,g'`
