#! /usr/bin/env bash

# Check for git on the system
git=`which git`

if [ "$git" = "" ] ; then
  echo "ERROR! You must have git installed to use this script!!!"
  exit
fi

git_branch=`git branch | grep "*" | awk '{print $2}' | sed 's,\/.*,,'`

if [ "$git_branch" = "master" ] || [[ "$git_branch" =~ feature ]] ; then

  # If we're on the master branch or a feature branch, use git describe
  # to get the last annotated tag and the commit to make major.minor.patch

  git describe | awk -F"-" '{print $1"."$2}'

else

  # Any other branches should have an annotated tag that specifies
  # major.minor.patch, so we just remove the commit and hash

  git describe --abbrev=0

fi
