#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively clone project.
#------------------------------------------------------------------------------#

# Clone the project
git clone --recursive $1

# Parse off the name of the project
project=`echo $1 | sed 's,^.*:,,;s,.git,,'`

# Checkout master in each submodule.  The default behavior leaves
# the submodules headless, which can be disturbing to the average user...
cd $project && git submodule foreach --recursive "
	git chekcout master
";
